// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7Pg1WGdplkcrSQkl2Sij6LenW5prUbg',
    appId: '1:463732718859:web:98649460981b2ab542760e',
    messagingSenderId: '463732718859',
    projectId: 'healthmonitoring-database',
    authDomain: 'healthmonitoring-database.firebaseapp.com',
    storageBucket: 'healthmonitoring-database.appspot.com',
    measurementId: 'G-S26ZGJNFJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOX87goD4aAN7gihOnXnt6NBhJR4ttdCg',
    appId: '1:463732718859:android:3e0d22b32bf2efbd42760e',
    messagingSenderId: '463732718859',
    projectId: 'healthmonitoring-database',
    storageBucket: 'healthmonitoring-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8Reb4A2BQFYGkTmiIXyZuZwsiRMEN1g',
    appId: '1:463732718859:ios:de10b3382d83157942760e',
    messagingSenderId: '463732718859',
    projectId: 'healthmonitoring-database',
    storageBucket: 'healthmonitoring-database.appspot.com',
    iosBundleId: 'com.example.group4App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8Reb4A2BQFYGkTmiIXyZuZwsiRMEN1g',
    appId: '1:463732718859:ios:de10b3382d83157942760e',
    messagingSenderId: '463732718859',
    projectId: 'healthmonitoring-database',
    storageBucket: 'healthmonitoring-database.appspot.com',
    iosBundleId: 'com.example.group4App',
  );
}
